# Map keyword "trigger" terms to search filters
"16-19":
  phases:
    - sixth_form_or_college
    - secondary
"visa":
  visa_sponsorship_availability:
    - "true"
"visa sponsorship":
  visa_sponsorship_availability:
    - "true"
"sponsorship":
  visa_sponsorship_availability:
    - "true"
"accounting teacher":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Accounting
"art":
  subjects:
    - Art and design
"assistant head":
  teaching_job_roles:
    - assistant_headteacher
"assistant headteacher":
  teaching_job_roles:
    - assistant_headteacher
"assistant head teacher":
  teaching_job_roles:
    - assistant_headteacher
"biology":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Biology
"business studies":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Business studies
"ceo":
  teaching_job_roles:
    - headteacher
"chemistry":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Chemistry
"citizenship":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Citizenship
"classics":
  subjects:
    - Classics
"computer":
  subjects:
    - Computing
    - ICT
"computing":
  subjects:
    - Computing
    - ICT
"control":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Design and technology
"dance":
  subjects:
    - Dance
"deputy":
  teaching_job_roles:
    - deputy_headteacher
"deputy head":
  teaching_job_roles:
    - deputy_headteacher
"deputy headteacher":
  teaching_job_roles:
    - deputy_headteacher
"deputy head teacher":
  teaching_job_roles:
    - deputy_headteacher
"design":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Art and design
    - Design and technology
"drama":
  subjects:
    - Drama
"dt":
  subjects:
    - Design and technology
"early career teacher":
  ect_statuses:
    - ect_suitable
"early career teachers":
  ect_statuses:
    - ect_suitable
"early years":
  phases:
    - primary
"ect":
  ect_statuses:
    - ect_suitable
"ects":
  ect_statuses:
    - ect_suitable
"english":
  subjects:
    - English
"eyfs":
  phases:
    - primary
"fe":
  phases:
    - sixth_form_or_college
"film":
  subjects:
    - Media studies
"finance teacher":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Accounting
"food technology":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Food technology
"french":
  subjects:
    - French
"full time":
  working_patterns:
    - full_time
"further education":
  phases:
    - sixth_form_or_college
"geography":
  subjects:
    - Geography
"german":
  subjects:
    - German
"greek":
  subjects:
    - Classics
"head of english":
  teaching_job_roles:
    - head_of_department_or_curriculum
"head of history":
  teaching_job_roles:
    - head_of_department_or_curriculum
"head of maths":
  teaching_job_roles:
    - head_of_department_or_curriculum
"head of mfl":
  teaching_job_roles:
    - head_of_department_or_curriculum
"head of school":
  teaching_job_roles:
    - headteacher
"head of science":
  teaching_job_roles:
    - head_of_department_or_curriculum
"head of":
  teaching_job_roles:
    - head_of_department_or_curriculum
"head of sixth form":
  teaching_job_roles:
    - head_of_year_or_phase
"head of key stage":
  teaching_job_roles:
    - head_of_year_or_phase
"head of ks":
  teaching_job_roles:
    - head_of_year_or_phase
"head of ks1":
  teaching_job_roles:
    - head_of_year_or_phase
"head of ks2":
  teaching_job_roles:
    - head_of_year_or_phase
"head of ks3":
  teaching_job_roles:
    - head_of_year_or_phase
"head of ks4":
  teaching_job_roles:
    - head_of_year_or_phase
"head of ks5":
  teaching_job_roles:
    - head_of_year_or_phase
"head of year":
  teaching_job_roles:
    - head_of_year_or_phase
"head teacher":
  teaching_job_roles:
    - headteacher
"headteacher":
  teaching_job_roles:
    - headteacher
"health":
  subjects:
    - Health and social care
"history":
  subjects:
    - History
"hlta":
  teaching_support_job_roles:
    - teaching_assistant
"hospitality":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Food technology
"humanities":
  subjects:
    - Humanities
    - History
    - Geography
    - Law
    - Health and Social Care
    - Religious studies
    - Sociology
    - Psychology
    - Social sciences
    - Philosophy
    - Politics
"ict":
  subjects:
    - Computing
    - ICT
"it":
  subjects:
    - Computing
    - ICT
"key stage 1":
  phases:
    - primary
"key stage 2":
  phases:
    - primary
    - middle
"key stage 3":
  phases:
    - middle
    - secondary
"key stage 4":
  phases:
    - secondary
"key stage 5":
  phases:
    - secondary
    - sixth_form_or_college
"ks1":
  phases:
    - primary
"ks2":
  phases:
    - primary
    - middle
"ks3":
  phases:
    - middle
    - secondary
"ks4":
  phases:
    - secondary
"ks5":
  phases:
    - secondary
    - sixth_form_or_college
"languages":
  subjects:
    - Languages
    - French
    - German
    - Spanish
    - Mandarin
"latin":
  subjects:
    - Classics
"law":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Law
"leader":
  teaching_job_roles:
    - headteacher
    - deputy_headteacher
    - assistant_headteacher
    - head_of_year_or_phase
    - head_of_department_or_curriculum
"leadership":
  teaching_job_roles:
    - headteacher
    - deputy_headteacher
    - assistant_headteacher
    - head_of_year_or_phase
    - head_of_department_or_curriculum
"learning support assistant":
  teaching_support_job_roles:
    - teaching_assistant
    - education_support
"literacy":
  phases:
    - primary
  subjects:
    - English
"literature":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - English
"lsa":
  teaching_support_job_roles:
    - teaching_assistant
    - education_support
"mandarin":
  subjects:
    - Mandarin
"math":
  subjects:
    - Mathematics
    - Statistics
"mathematics":
  subjects:
    - Mathematics
    - Statistics
"maths":
  subjects:
    - Mathematics
    - Statistics
"media":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Media studies
"mfl":
  subjects:
    - Languages
    - French
    - German
    - Spanish
    - Mandarin
"middle leader":
  teaching_job_roles:
    - head_of_year_or_phase
    - head_of_department_or_curriculum
"middle leadership":
  teaching_job_roles:
    - head_of_year_or_phase
    - head_of_department_or_curriculum
"middle school":
  phases:
    - middle
"middle schools":
  phases:
    - middle
"music":
  subjects:
    - Music
"newly qualified teacher":
  ect_statuses:
    - ect_suitable
"newly qualified teachers":
  ect_statuses:
    - ect_suitable
"nqt":
  ect_statuses:
    - ect_suitable
"nqts":
  ect_statuses:
    - ect_suitable
"numeracy":
  phases:
    - primary
  subjects:
    - Mathematics
"nursery":
  phases:
    - primary
"part time":
  working_patterns:
    - part_time
"pe":
  subjects:
    - Physical education
"performing":
  subjects:
    - Drama
"phase leader":
  teaching_job_roles:
    - head_of_year_or_phase
"philosophy":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Philosophy
"phonics":
  phases:
    - primary
  subjects:
    - English
"photography":
  subjects:
    - Art and design
    - Media studies
"physical education":
  subjects:
    - Physical education
"physics":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Physics
"politics":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Politics
"primary":
  phases:
    - primary
"primary school":
  phases:
    - primary
"primary schools":
  phases:
    - primary
"principal":
  teaching_job_roles:
    - headteacher
"product":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Design and technology
"pshe":
  subjects:
    - Relationships and sex education
"psychology":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Psychology
"re":
  subjects:
    - Religious education
"reception":
  phases:
    - primary
"relationships":
  subjects:
    - Relationships and sex education
"religion":
  subjects:
    - Religious education
"religious education":
  subjects:
    - Religious education
"religious studies":
  subjects:
    - Religious education
"rs":
  subjects:
    - Religious education
"rse":
  subjects:
    - Relationships and sex education
"russian":
  subjects:
    - Languages
"science":
  subjects:
    - Science
    - Biology
    - Chemistry
    - Physics
"secondary":
  phases:
    - secondary
"secondary school":
  phases:
    - secondary
"secondary schools":
  phases:
    - secondary
"sen":
  teaching_job_roles:
    - sendco
"senco":
  teaching_job_roles:
    - sendco
"send":
  teaching_job_roles:
    - sendco
"sendco":
  teaching_job_roles:
    - sendco
"senior leader":
  teaching_job_roles:
    - headteacher
    - deputy_headteacher
    - assistant_headteacher
"senior leadership":
  teaching_job_roles:
    - headteacher
    - deputy_headteacher
    - assistant_headteacher
"senior leadership team":
  teaching_job_roles:
    - headteacher
    - deputy_headteacher
    - assistant_headteacher
"sex education":
  subjects:
    - Relationships and sex education
"sixth form":
  phases:
    - sixth_form_or_college
    - secondary
"slt":
  teaching_job_roles:
    - headteacher
    - deputy_headteacher
    - assistant_headteacher
"social care":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Health and social care
"social science":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Social sciences
    - Sociology
"social sciences":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Social sciences
    - Sociology
"sociology":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Social sciences
    - Sociology
"spanish":
  subjects:
    - Spanish
"special educational needs":
  teaching_job_roles:
    - sendco
"special educational needs co-ordinator":
  teaching_job_roles:
    - sendco
"special educational needs coordinator":
  teaching_job_roles:
    - sendco
"sport":
  subjects:
    - Physical education
"sports":
  subjects:
    - Physical education
"statistics":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Statistics
"suitable for ect":
  ect_statuses:
    - ect_suitable
"suitable for ects":
  ect_statuses:
    - ect_suitable
"suitable for nqt":
  ect_statuses:
    - ect_suitable
"suitable for nqts":
  ect_statuses:
    - ect_suitable
"support":
  teaching_support_job_roles:
    - education_support
"systems":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Design and technology
"ta":
  teaching_support_job_roles:
    - teaching_assistant
"teach":
  teaching_job_roles:
    - teacher
"teacher":
  teaching_job_roles:
    - teacher
"teacher of accounting":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Accounting
"teacher of finance":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Accounting
"teachers":
  teaching_job_roles:
    - teacher
"teaching":
  teaching_job_roles:
    - teacher
"teaching assistant":
  teaching_support_job_roles:
    - teaching_assistant
"teaching assistants":
  teaching_support_job_roles:
    - teaching_assistant
"textiles":
  phases:
    - secondary
    - sixth_form_or_college
  subjects:
    - Design and technology
"theatre":
  subjects:
    - Drama
"tlr":
  teaching_job_roles:
    - head_of_year_or_phase
    - head_of_department_or_curriculum
