amazon_s3_documents:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon_s3_images_and_logos:
  service: Disk
  root: <%= Rails.root.join("storage") %>

azure_storage_documents:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

azure_storage_images_and_logos:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
