# This file lists all the attributes to be exported, including those to be anonymised.
shared:
  account_requests:
    - id
    - full_name
    - email
    - organisation_name
    - organisation_identifier
    - created_at
    - updated_at
  employments:
    - id
    - employment_type
    - organisation
    - job_title
    - salary
    - subjects
    - current_role
    - main_duties
    - started_on
    - ended_on
    - job_application_id
    - reason_for_break
    - created_at
    - updated_at
  equal_opportunities_reports:
    - id
    - vacancy_id
    - total_submissions
    - disability_no
    - disability_prefer_not_to_say
    - disability_yes
    - gender_man
    - gender_other
    - gender_prefer_not_to_say
    - gender_woman
    - gender_other_descriptions
    - orientation_bisexual
    - orientation_gay_or_lesbian
    - orientation_heterosexual
    - orientation_other
    - orientation_prefer_not_to_say
    - orientation_other_descriptions
    - ethnicity_asian
    - ethnicity_black
    - ethnicity_mixed
    - ethnicity_other
    - ethnicity_prefer_not_to_say
    - ethnicity_white
    - ethnicity_other_descriptions
    - religion_buddhist
    - religion_christian
    - religion_hindu
    - religion_jewish
    - religion_muslim
    - religion_none
    - religion_other
    - religion_prefer_not_to_say
    - religion_sikh
    - religion_other_descriptions
    - created_at
    - updated_at
    - age_under_twenty_five
    - age_twenty_five_to_twenty_nine
    - age_prefer_not_to_say
    - age_thirty_to_thirty_nine
    - age_forty_to_forty_nine
    - age_fifty_to_fifty_nine
    - age_sixty_and_over
  feedbacks:
    - id
    - created_at
    - updated_at
    - feedback_type
    - rating
    - recaptcha_score
    - relevant_to_user
    - search_criteria
    - job_alert_vacancy_ids
    - unsubscribe_reason
    - email
    - user_participation_response
    - visit_purpose
    - job_application_id
    - jobseeker_id
    - publisher_id
    - subscription_id
    - vacancy_id
    - close_account_reason
    - close_account_reason_comment
  job_applications:
    - id
    - status
    - created_at
    - updated_at
    - submitted_at
    - jobseeker_id
    - vacancy_id
    - completed_steps
    - draft_at
    - shortlisted_at
    - unsuccessful_at
    - withdrawn_at
    - first_name
    - last_name
    - previous_names
    - street_address
    - city
    - postcode
    - phone_number
    - teacher_reference_number
    - national_insurance_number
    - qualified_teacher_status
    - qualified_teacher_status_year
    - statutory_induction_complete
    - personal_statement
    - support_needed
    - support_needed_details
    - close_relationships
    - close_relationships_details
    - right_to_work_in_uk
    - further_instructions
    - rejection_reasons
    - gaps_in_employment
    - gaps_in_employment_details
    - reviewed_at
    - country
    - email_address
    - withdrawn_by_closing_account
  jobseekers:
    - id
    - email
    - reset_password_token
    - reset_password_sent_at
    - sign_in_count
    - current_sign_in_at
    - last_sign_in_at
    - confirmation_token
    - confirmed_at
    - confirmation_sent_at
    - unconfirmed_email
    - failed_attempts
    - unlock_token
    - locked_at
    - created_at
    - updated_at
    - account_closed_on
  local_authority_publisher_schools:
    - id
    - publisher_preference_id
    - school_id
    - created_at
    - updated_at
  notifications:
    - id
    - recipient_type
    - recipient_id
    - type
    - read_at
    - created_at
    - updated_at
  organisations:
    - id
    - type
    - name
    - description
    - urn
    - uid
    - phase
    - url
    - minimum_age
    - maximum_age
    - address
    - town
    - county
    - postcode
    - locality
    - address3
    - geolocation
    - gias_data
    - created_at
    - updated_at
    - readable_phases
    - website
    - region
    - detailed_school_type
    - school_type
    - local_authority_code
    - group_type
    - local_authority_within
    - establishment_status
  organisation_publisher_preferences:
    - id
    - organisation_id
    - publisher_preference_id
    - created_at
    - updated_at
  organisation_publishers:
    - id
    - organisation_id
    - publisher_id
    - created_at
    - updated_at
  organisation_vacancies:
    - id
    - organisation_id
    - vacancy_id
    - created_at
    - updated_at
  publishers:
    - id
    - oid
    - accepted_terms_at
    - email
    - last_activity_at
    - family_name
    - given_name
    - created_at
    - updated_at
  publisher_preferences:
    - id
    - publisher_id
    - organisation_id
    - created_at
    - updated_at
  qualifications:
    - id
    - created_at
    - updated_at
    - category
    - finished_studying
    - finished_studying_details
    - grade
    - institution
    - name
    - subject
    - year
    - job_application_id
  qualification_results:
    - id
    - qualification_id
    - subject
    - grade
    - created_at
    - updated_at
  references:
    - id
    - name
    - job_title
    - organisation
    - relationship
    - email
    - phone_number
    - job_application_id
    - created_at
    - updated_at
  saved_jobs:
    - id
    - jobseeker_id
    - vacancy_id
    - created_at
    - updated_at
  school_group_memberships:
    - id
    - school_id
    - school_group_id
    - created_at
    - updated_at
  subscriptions:
    - id
    - email
    - frequency
    - search_criteria
    - created_at
    - updated_at
    - recaptcha_score
    - active
    - unsubscribed_at
  vacancies:
    - id
    - job_title
    - slug
    - job_advert
    - benefits
    - starts_on
    - ends_on
    - contact_email
    - status
    - publish_on
    - created_at
    - updated_at
    - application_link
    - working_patterns
    - listed_elsewhere
    - hired_status
    - stats_updated_at
    - publisher_id
    - expires_at
    - actual_salary
    - salary
    - legacy_job_roles
    - about_school
    - subjects
    - school_visits
    - how_to_apply
    - initially_indexed
    - job_location
    - readable_job_location
    - job_roles
    - contact_number
    - publisher_organisation_id
    - starts_asap
    - contract_type
    - contract_type_duration
    - enable_job_applications
    - personal_statement_guidance
    - end_listing_reason
    - candidate_hired_from
    - completed_steps
    - working_patterns_details
    - phase
    - key_stages
