# This file lists all the attributes to be exported, including those to be anonymised.
shared:
  :active_storage_attachments:
    - id
    - name
    - record_type
    - record_id
    - blob_id
    - created_at
  :active_storage_blobs:
    - id
    - key
    - filename
    - content_type
    - metadata
    - service_name
    - byte_size
    - checksum
    - created_at
  employments:
    - id
    - employment_type
    - organisation
    - job_title
    - subjects
    - is_current_role
    - main_duties
    - started_on
    - ended_on
    - job_application_id
    - reason_for_break
    - created_at
    - updated_at
    - jobseeker_profile_id
    - reason_for_leaving
  equal_opportunities_reports:
    - id
    - vacancy_id
    - total_submissions
    - disability_no
    - disability_prefer_not_to_say
    - disability_yes
    - gender_man
    - gender_other
    - gender_prefer_not_to_say
    - gender_woman
    - gender_other_descriptions
    - orientation_bisexual
    - orientation_gay_or_lesbian
    - orientation_heterosexual
    - orientation_other
    - orientation_prefer_not_to_say
    - orientation_other_descriptions
    - ethnicity_asian
    - ethnicity_black
    - ethnicity_mixed
    - ethnicity_other
    - ethnicity_prefer_not_to_say
    - ethnicity_white
    - ethnicity_other_descriptions
    - religion_buddhist
    - religion_christian
    - religion_hindu
    - religion_jewish
    - religion_muslim
    - religion_none
    - religion_other
    - religion_prefer_not_to_say
    - religion_sikh
    - religion_other_descriptions
    - created_at
    - updated_at
    - age_under_twenty_five
    - age_twenty_five_to_twenty_nine
    - age_prefer_not_to_say
    - age_thirty_to_thirty_nine
    - age_forty_to_forty_nine
    - age_fifty_to_fifty_nine
    - age_sixty_and_over
  feedbacks:
    - id
    - created_at
    - updated_at
    - feedback_type
    - rating
    - recaptcha_score
    - relevant_to_user
    - search_criteria
    - job_alert_vacancy_ids
    - unsubscribe_reason
    - email
    - user_participation_response
    - visit_purpose
    - job_application_id
    - jobseeker_id
    - publisher_id
    - subscription_id
    - vacancy_id
    - close_account_reason
    - close_account_reason_comment
    - occupation
    - origin_path
    - job_found_unsubscribe_reason_comment
  job_applications:
    - id
    - status
    - created_at
    - updated_at
    - submitted_at
    - jobseeker_id
    - vacancy_id
    - completed_steps
    - draft_at
    - shortlisted_at
    - unsuccessful_at
    - interviewing_at
    - withdrawn_at
    - offered_at
    - declined_at
    - rejected_at
    - unsuccessful_interview_at
    - interview_feedback_received_at
    - interview_feedback_received
    - first_name
    - last_name
    - previous_names
    - street_address
    - city
    - postcode
    - phone_number
    - teacher_reference_number
    - national_insurance_number
    - qualified_teacher_status
    - qts_age_range_and_subject
    - qualified_teacher_status_year
    - is_statutory_induction_complete
    - personal_statement
    - is_support_needed
    - support_needed_details
    - has_close_relationships
    - close_relationships_details
    - has_right_to_work_in_uk
    - further_instructions
    - rejection_reasons
    - gaps_in_employment_details
    - reviewed_at
    - country
    - email_address
    - withdrawn_by_closing_account
    - has_safeguarding_issue
    - safeguarding_issue_details
    - imported_steps
    - statutory_induction_complete_details
    - following_religion
    - religious_reference_type
    - faith
    - place_of_worship
    - religious_referee_name
    - religious_referee_address
    - religious_referee_role
    - religious_referee_email
    - religious_referee_phone
    - baptism_address
    - baptism_date
    - ethos_and_aims
    - working_patterns
    - working_pattern_details
    - notify_before_contact_referers
    - type
  job_preferences_locations:
    - id
    - job_preferences_id
    - name
    - radius
    - area
    - created_at
    - updated_at
  jobseeker_profiles:
    - id
    - created_at
    - updated_at
    - jobseeker_id
    - about_you
    - qualified_teacher_status
    - qts_age_range_and_subject
    - qualified_teacher_status_year
    - active
    - requested_hidden_profile
    - is_statutory_induction_complete
    - teacher_reference_number
    - statutory_induction_complete_details
  jobseeker_profile_excluded_organisations:
    - id
    - jobseeker_profile_id
    - organisation_id
    - created_at
    - updated_at
  jobseekers:
    - id
    - email
    - sign_in_count
    - current_sign_in_at
    - last_sign_in_at
    - created_at
    - updated_at
    - account_closed_on
    - govuk_one_login_id
    - account_merge_confirmation_code_generated_at
    - email_opt_out
    - email_opt_out_reason
    - email_opt_out_comment
  job_preferences:
    - id
    - roles
    - phases
    - key_stages
    - subjects
    - working_patterns
    - completed_steps
    - builder_completed
    - created_at
    - updated_at
    - jobseeker_profile_id
    - working_pattern_details
  local_authority_publisher_schools:
    - id
    - publisher_preference_id
    - school_id
    - created_at
    - updated_at
  location_polygons:
    - id
    - name
    - location_type
    - area
    - centroid
    - created_at
    - updated_at
  organisations:
    - id
    - type
    - name
    - description
    - safeguarding_information
    - urn
    - uid
    - phase
    - url
    - email
    - minimum_age
    - maximum_age
    - address
    - town
    - county
    - postcode
    - locality
    - address3
    - geopoint
    - gias_data
    - created_at
    - updated_at
    - url_override
    - region
    - detailed_school_type
    - school_type
    - local_authority_code
    - group_type
    - local_authority_within
    - establishment_status
  organisation_publisher_preferences:
    - id
    - organisation_id
    - publisher_preference_id
    - created_at
    - updated_at
  organisation_publishers:
    - id
    - organisation_id
    - publisher_id
    - created_at
    - updated_at
  organisation_vacancies:
    - id
    - organisation_id
    - vacancy_id
    - created_at
    - updated_at
  publishers:
    - id
    - oid
    - accepted_terms_at
    - acknowledged_candidate_profiles_interstitial
    - email
    - email_opt_out
    - last_activity_at
    - family_name
    - given_name
    - created_at
    - updated_at
  publisher_ats_api_clients:
    - id
    - name
    - last_rotated_at
    - created_at
    - updated_at
  publisher_preferences:
    - id
    - publisher_id
    - organisation_id
    - created_at
    - updated_at
  qualifications:
    - id
    - created_at
    - updated_at
    - category
    - finished_studying
    - finished_studying_details
    - grade
    - institution
    - name
    - subject
    - year
    - month
    - job_application_id
    - jobseeker_profile_id
    - awarding_body
  qualification_results:
    - id
    - qualification_id
    - subject
    - grade
    - awarding_body
    - created_at
    - updated_at
  references:
    - id
    - name
    - job_title
    - organisation
    - relationship
    - email
    - phone_number
    - job_application_id
    - created_at
    - updated_at
    - is_most_recent_employer
  job_references:
    - id
    - created_at
    - updated_at
    - allegations
    - complete
    - can_give_reference
    - email
    - is_reference_sharable
    - reference_request_id
    - employment_start_date
    - employment_end_date
    - currently_employed
    - would_reemploy_current
    - would_reemploy_any
    - name
    - not_provided_reason
    - job_title
    - phone_number
    - organisation
    - under_investigation
    - warnings
    - not_fit_to_practice
    - able_to_undertake_role
    - punctuality
    - working_relationships
    - customer_care
    - adapt_to_change
    - deal_with_conflict
    - prioritise_workload
    - team_working
    - communication
    - problem_solving
    - general_attitude
    - technical_competence
    - leadership
    - how_do_you_know_the_candidate
    - reason_for_leaving
    - would_reemploy_current_reason
    - would_reemploy_any_reason
    - under_investigation_details
    - warning_details
    - unable_to_undertake_reason
  reference_requests:
    - id
    - reference_id
    - status
    - created_at
    - updated_at
    - marked_as_complete
    - reminder_sent
    - email
  religious_reference_requests:
    - id
    - job_application_id
    - status
    - created_at
    - updated_at
  saved_jobs:
    - id
    - jobseeker_id
    - vacancy_id
    - created_at
    - updated_at
  school_group_memberships:
    - id
    - school_id
    - school_group_id
    - created_at
    - updated_at
  subscriptions:
    - id
    - email
    - frequency
    - search_criteria
    - created_at
    - updated_at
    - recaptcha_score
    - unsubscribed_at
  vacancies:
    - id
    - job_title
    - slug
    - job_advert
    - benefits
    - benefits_details
    - start_date_type
    - starts_on
    - earliest_start_date
    - latest_start_date
    - other_start_date_details
    - contact_email
    - publish_on
    - created_at
    - updated_at
    - discarded_at
    - application_link
    - working_patterns
    - listed_elsewhere
    - hired_status
    - stats_updated_at
    - publisher_id
    - expires_at
    - actual_salary
    - salary
    - about_school
    - subjects
    - school_visits
    - ect_status
    - contact_number
    - publisher_organisation_id
    - contract_type
    - fixed_term_contract_duration
    - parental_leave_cover_contract_duration
    - enable_job_applications
    - completed_steps
    - working_patterns_details
    - full_time_details
    - part_time_details
    - phases
    - key_stages
    - geolocation
    - external_source
    - external_reference
    - external_advert_url
    - job_location
    - job_roles
    - starts_asap
    - pay_scale
    - receive_applications
    - application_email
    - contact_number_provided
    - skills_and_experience
    - school_offer
    - further_details_provided
    - further_details
    - include_additional_documents
    - visa_sponsorship_available
    - is_parental_leave_cover
    - is_job_share
    - hourly_rate
    - flexi_working
    - extension_reason
    - other_extension_reason_details
    - religion_type
    - flexi_working_details_provided
    - type
    - publisher_ats_api_client_id
    - anonymise_applications
  failed_imported_vacancies:
    - id
    - import_errors
    - source
    - created_at
    - updated_at
    - external_reference
    - vacancy
  personal_details:
    - id
    - jobseeker_profile_id
    - first_name
    - last_name
    - phone_number_provided
    - phone_number
    - completed_steps
    - created_at
    - has_right_to_work_in_uk
    - updated_at
  :training_and_cpds:
    - id
    - name
    - provider
    - grade
    - year_awarded
    - created_at
    - updated_at
    - jobseeker_profile_id
    - job_application_id
    - course_length
  :noticed_notifications:
    - id
    - type
    - event_id
    - recipient_type
    - recipient_id
    - read_at
    - seen_at
    - created_at
    - updated_at
  :noticed_events:
    - id
    - type
    - record_type
    - record_id
    - params
    - created_at
    - updated_at
    - notifications_count
  :professional_body_memberships:
    - id
    - created_at
    - updated_at
    - name
    - membership_type
    - membership_number
    - year_membership_obtained
    - exam_taken
    - jobseeker_profile_id
    - job_application_id
  :self_disclosure_requests:
    - id
    - job_application_id
    - status
    - created_at
    - updated_at
    - marked_as_complete
  :self_disclosures:
    - id
    - self_disclosure_request_id
    - created_at
    - updated_at
    - name
    - previous_names
    - address_line_1
    - address_line_2
    - city
    - country
    - postcode
    - phone_number
    - date_of_birth
    - has_unspent_convictions
    - has_spent_convictions
    - is_barred
    - has_been_referred
    - is_known_to_children_services
    - has_been_dismissed
    - has_been_disciplined
    - has_been_disciplined_by_regulatory_body
    - agreed_for_processing
    - agreed_for_criminal_record
    - agreed_for_organisation_update
    - agreed_for_information_sharing
    - true_and_complete
  :messages:
    - id
    - sender_id
    - conversation_id
    - created_at
    - updated_at
    - type
    - read
  :conversations:
    - id
    - job_application_id
    - created_at
    - updated_at
    - archived
    - last_message_at
    - has_unread_jobseeker_messages
  :action_text_rich_texts:
  - body_ciphertext
  - migrated_body