# This file lists the attributes which should be anonymised when exported.
# If an attribute is not listed in analytics.yml, it will not exported, even if it is listed here.
shared:
  documents:
    - id
    - vacancy_id
  equal_opportunities_reports:
    - id
    - vacancy_id
  employments:
    - id
    - organisation
    - job_title
    - main_duties
    - job_application_id
  feedbacks:
    - id
    - email
    - job_application_id
    - jobseeker_id
    - publisher_id
    - subscription_id
    - vacancy_id
  job_applications:
    - id
    - jobseeker_id
    - vacancy_id
    - first_name
    - last_name
    - previous_names
    - street_address
    - city
    - postcode
    - phone_number
    - teacher_reference_number
    - national_insurance_number
    - personal_statement
    - support_needed_details
    - close_relationships_details
    - further_instructions
    - rejection_reasons
    - gaps_in_employment_details
    - email_address
  jobseekers:
    - id
    - email
    - unconfirmed_email
  local_authority_publisher_schools:
    - id
    - publisher_preference_id
    - school_id
  notifications:
    - id
    - recipient_id
  organisations:
    - id
  organisation_publisher_preferences:
    - id
    - organisation_id
    - publisher_preference_id
  organisation_publishers:
    - id
    - organisation_id
    - publisher_id
  organisation_vacancies:
    - id
    - organisation_id
    - vacancy_id
  publishers:
    - id
    - oid
    - email
    - family_name
    - given_name
  publisher_preferences:
    - id
    - publisher_id
    - organisation_id
  qualifications:
    - id
    - finished_studying_details
    - job_application_id
  qualification_results:
    - id
    - qualification_id
  references:
    - id
    - name
    - job_title
    - organisation
    - email
    - phone_number
    - job_application_id
  saved_jobs:
    - id
    - jobseeker_id
    - vacancy_id
  school_group_memberships:
    - id
    - school_id
    - school_group_id
  subscriptions:
    - id
    - email
  vacancies:
    - id
    - contact_email
    - publisher_id
    - publisher_organisation_id
