shared:
  - api_queried
  - copied_to_clipboard
  - failed_dsi_sign_in_attempt
  - form_validation_failed
  - google_geocoding_api_hit
  - job_alert_subscription_created
  - job_alert_subscription_unsubscribed
  - job_alert_subscription_updated
  - jobseeker_account_closed
  - jobseeker_application_shortlisted
  - jobseeker_application_submitted
  - jobseeker_application_unsuccessful
  - jobseeker_changed_govuk_one_login_email
  - jobseeker_changed_govuk_one_login_id
  - jobseeker_disable_profile_due_to_new_fields
  - jobseeker_disable_inactive_profile
  - jobseeker_failed_govuk_one_login_sign_in
  - jobseeker_inactive_account
  - jobseeker_inactive_profile_warning
  - jobseeker_job_listing_ended_early
  - jobseeker_request_account_transfer
  - jobseeker_self_disclosure
  - jobseeker_sign_in_attempt
  - jobseeker_subscription_alert
  - jobseeker_subscription_confirmation
  - jobseeker_subscription_update
  - jobseeker_successful_govuk_one_login_sign_in
  - jobseeker_draft_application_only
  - jobseeker_unapplied_saved_vacancy
  - jobseeker_peak_times_reminder
  - jobseeker_message_received
  - publisher_applications_received
  - publisher_collect_references
  - publisher_inform_applicant_about_references
  - publisher_invite_to_apply
  - publisher_invite_user
  - publisher_job_application_data_expiry
  - publisher_messages_received
  - publisher_prompt_for_feedback
  - publisher_reference_received
  - publisher_self_disclosure_received
  - publisher_sign_in_fallback
  - publisher_vacancy_relisted
  - search_performed
  - successful_publisher_sign_in_attempt
  - support_user_sign_in_fallback
  - supporting_document_created
  - supporting_document_deleted
  - supporting_document_replaced
  - tracked_link_clicked
  - vacancy_apply_clicked
  - vacancy_create_job_alert_clicked
  - vacancy_document_downloaded
