---
:shared:
  :friendly_id_slugs:
  - id
  - slug
  - sluggable_id
  - sluggable_type
  - scope
  - created_at
  :versions:
  - id
  - item_type
  - item_id
  - event
  - whodunnit
  - object
  - created_at
  - object_changes
  :sessions:
  - id
  - session_id
  - data
  - created_at
  - updated_at
  :active_storage_variant_records:
  - id
  - blob_id
  - variation_digest
  :action_text_rich_texts:
    - id
    - name
    - body
    - record_type
    - record_id
    - created_at
    - updated_at
  :message_templates:
    - id
    - publisher_id
    - name
    - created_at
    - updated_at
    - template_type
  :school_group_memberships:
  - do_not_delete
  :references:
  - name_ciphertext
  - job_title_ciphertext
  - organisation_ciphertext
  - email_ciphertext
  - phone_number_ciphertext
  :publisher_ats_api_clients:
  - api_key
  :personal_details:
  - first_name_ciphertext
  - last_name_ciphertext
  - phone_number_ciphertext
  :notes:
  - id
  - content
  - publisher_id
  - job_application_id
  - created_at
  - updated_at
  - discarded_at
  :markers:
  - id
  - vacancy_id
  - organisation_id
  - geopoint
  - created_at
  - updated_at
  :jobseeker_profiles:
  - teacher_reference_number_ciphertext
  - qualified_teacher_status_details
  :job_preferences:
  - willing_to_relocate
  :job_applications:
  - qualified_teacher_status_details
  - disability
  - gender
  - gender_description
  - orientation
  - orientation_description
  - ethnicity
  - ethnicity_description
  - religion
  - religion_description
  - age
  - first_name_ciphertext
  - last_name_ciphertext
  - previous_names_ciphertext
  - street_address_ciphertext
  - city_ciphertext
  - postcode_ciphertext
  - phone_number_ciphertext
  - teacher_reference_number_ciphertext
  - national_insurance_number_ciphertext
  - personal_statement_ciphertext
  - support_needed_details_ciphertext
  - close_relationships_details_ciphertext
  - further_instructions_ciphertext
  - rejection_reasons_ciphertext
  - gaps_in_employment_details_ciphertext
  - in_progress_steps
  - employment_history_section_completed
  - qualifications_section_completed
  - place_of_worship_ciphertext
  - religious_referee_name_ciphertext
  - religious_referee_address_ciphertext
  - religious_referee_role_ciphertext
  - religious_referee_email_ciphertext
  - religious_referee_phone_ciphertext
  - faith_ciphertext
  - baptism_address_ciphertext
  - baptism_date_ciphertext
  - ethos_and_aims_ciphertext
  :employments:
  - organisation_ciphertext
  - job_title_ciphertext
  - main_duties_ciphertext
  :emergency_login_keys:
  - id
  - not_valid_after
  - created_at
  - updated_at
  - owner_type
  - owner_id
  :alert_runs:
  - id
  - subscription_id
  - run_on
  - job_id
  - created_at
  - updated_at
  - status
  :vacancies:
  - readable_job_location
  - readable_phases
  - searchable_content
  - google_index_removed
  - expired_vacancy_feedback_email_sent_at
  :qualifications:
  - finished_studying_details_ciphertext
  :feedbacks:
  - comment
  - other_unsubscribe_reason_comment
  - visit_purpose_comment
  - category
  :support_users:
  - id
  - oid
  - email
  - given_name
  - family_name
  - created_at
  - updated_at
  :publishers:
  - family_name_ciphertext
  - given_name_ciphertext
  - dismissed_new_features_page_at
  - unsubscribed_from_expired_vacancy_prompt_at
  :jobseekers:
  - current_sign_in_ip_ciphertext
  - last_sign_in_ip_ciphertext
  - account_merge_confirmation_code
  - last_sign_in_ip
  - current_sign_in_ip
  :organisations:
  - gias_data_hash
  - slug
  - searchable_content
  :vacancy_analytics:
  - id
  - vacancy_id
  - referrer_counts
  - created_at
  - updated_at
  job_references:
    - token
    - employment_start_date_ciphertext
    - employment_end_date_ciphertext
    - punctuality_ciphertext
    - working_relationships_ciphertext
    - customer_care_ciphertext
    - adapt_to_change_ciphertext
    - deal_with_conflict_ciphertext
    - prioritise_workload_ciphertext
    - team_working_ciphertext
    - communication_ciphertext
    - problem_solving_ciphertext
    - general_attitude_ciphertext
    - technical_competence_ciphertext
    - leadership_ciphertext
    - under_investigation_ciphertext
    - warnings_ciphertext
    - allegations_ciphertext
    - not_fit_to_practice_ciphertext
    - able_to_undertake_role_ciphertext
    - how_do_you_know_the_candidate_ciphertext
    - reason_for_leaving_ciphertext
    - would_reemploy_current_reason_ciphertext
    - would_reemploy_any_reason_ciphertext
    - under_investigation_details_ciphertext
    - warning_details_ciphertext
    - unable_to_undertake_reason_ciphertext
  reference_requests:
    - token
  :job_application_batches:
  - id
  - vacancy_id
  - created_at
  - updated_at
  :batchable_job_applications:
  - id
  - job_application_id
  - created_at
  - updated_at
  - job_application_batch_id
  :self_disclosures:
  - name_ciphertext
  - previous_names_ciphertext
  - address_line_1_ciphertext
  - address_line_2_ciphertext
  - city_ciphertext
  - country_ciphertext
  - postcode_ciphertext
  - phone_number_ciphertext
  - date_of_birth_ciphertext
  - has_unspent_convictions_ciphertext
  - has_spent_convictions_ciphertext
  - is_barred_ciphertext
  - has_been_referred_ciphertext
  - is_known_to_children_services_ciphertext
  - has_been_dismissed_ciphertext
  - has_been_disciplined_ciphertext
  - has_been_disciplined_by_regulatory_body_ciphertext
  - agreed_for_processing_ciphertext
  - agreed_for_criminal_record_ciphertext
  - agreed_for_organisation_update_ciphertext
  - agreed_for_information_sharing_ciphertext
  - true_and_complete_ciphertext
  :subscriptions:
  - area
  - geopoint
  - radius_in_metres
  :conversations:
    - searchable_content
  :action_text_rich_texts:
    - body_ciphertext
    - migrated_body
