# This file lists the attributes which should be anonymised when exported.
# If an attribute is not listed in analytics.yml, it will not exported, even if it is listed here.
shared:
  employments:
    - organisation
    - job_title
    - main_duties
    - jobseeker_profile_id
  feedbacks:
    - email
    - jobseeker_id
    - publisher_id
  job_applications:
    - jobseeker_id
    - first_name
    - last_name
    - previous_names
    - street_address
    - city
    - postcode
    - phone_number
    - teacher_reference_number
    - national_insurance_number
    - personal_statement
    - support_needed_details
    - close_relationships_details
    - further_instructions
    - rejection_reasons
    - gaps_in_employment_details
    - email_address
    - religious_reference_type
    - faith
    - place_of_worship
    - religious_referee_name
    - religious_referee_address
    - religious_referee_role
    - religious_referee_email
    - religious_referee_phone
    - baptism_address
    - baptism_date
    - ethos_and_aims
    - has_lived_abroad
    - life_abroad_details
  jobseeker_profiles:
    - id
    - jobseeker_id
    - about_you
    - teacher_reference_number
  jobseeker_profile_excluded_organisations:
    - jobseeker_profile_id
  jobseekers:
    - id
    - email
    - govuk_one_login_id
  job_preferences:
    - jobseeker_profile_id
  organisations:
    - email
  organisation_publishers:
    - publisher_id
  publishers:
    - id
    - oid
    - email
    - family_name
    - given_name
  publisher_preferences:
    - publisher_id
  qualifications:
    - finished_studying_details
    - institution
    - jobseeker_profile_id
  references:
    - name
    - job_title
    - organisation
    - email
    - phone_number
  saved_jobs:
    - jobseeker_id
  subscriptions:
    - email
  vacancies:
    - application_email
    - contact_email
    - contact_number
    - publisher_id
  personal_details:
    - jobseeker_profile_id
    - first_name
    - last_name
    - phone_number
  self_disclosures:
    - name
    - previous_names
    - address_line_1
    - address_line_2
    - city
    - country
    - postcode
    - phone_number
    - date_of_birth
    - has_unspent_convictions
    - has_spent_convictions
    - is_barred
    - has_been_referred
    - is_known_to_children_services
    - has_been_dismissed
    - has_been_disciplined
    - has_been_disciplined_by_regulatory_body
    - agreed_for_processing
    - agreed_for_criminal_record
    - agreed_for_organisation_update
    - agreed_for_information_sharing
  job_references:
    - adapt_to_change
    - communication
    - customer_care
    - employment_start_date
    - employment_end_date
    - punctuality
    - working_relationships
    - not_provided_reason
    - deal_with_conflict
    - prioritise_workload
    - team_working
    - problem_solving
    - general_attitude
    - technical_competence
    - leadership
    - under_investigation
    - warnings
    - allegations
    - not_fit_to_practice
    - able_to_undertake_role
    - under_investigation_details
    - warning_details
    - unable_to_undertake_reason
