name: Copy PAAS databases to AKS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # 02:00 UTC

jobs:
  restore_db:
    name: Restore DB
    strategy:
      matrix:
        environment: [staging, production]
      max-parallel: 1
    uses: ./.github/workflows/restore-paas-db-to-aks.yml
    with:
      environment: ${{ matrix.environment }}
    secrets: inherit
